# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 22:56
from __future__ import unicode_literals

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UbigeoContinente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_ubigeo_reniec_continente', models.CharField(max_length=2, validators=[
                    django.core.validators.RegexValidator(message='Numero de 1 o 2 digitos', regex='^[0-9]{1,2}$')],
                                                                  verbose_name='Código Ubigeo Continente - RENIEC')),
                ('cod_ubigeo_inei_continente', models.CharField(max_length=2, validators=[
                    django.core.validators.RegexValidator(message='Numero de 1 o 2 digitos', regex='^[0-9]{1,2}$')],
                                                                verbose_name='Código Ubigeo Continente - INEI')),
                ('ubigeo_continente', models.CharField(max_length=100, verbose_name='Nombre Ubigeo Continente')),
            ],
            options={
                'verbose_name_plural': '1. Ubigeo Continentes',
            },
        ),
        migrations.CreateModel(
            name='UbigeoDepartamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_ubigeo_reniec_departamento', models.CharField(max_length=2, validators=[
                    django.core.validators.RegexValidator(message='Numero de 2 digitos', regex='^[0-9]{2}$')],
                                                                    verbose_name='Código Ubigeo Departamento - RENIEC')),
                ('cod_ubigeo_inei_departamento', models.CharField(max_length=2, validators=[
                    django.core.validators.RegexValidator(message='Numero de 2 digitos', regex='^[0-9]{2}$')],
                                                                  verbose_name='Código Ubigeo Departamento - INEI')),
                ('ubigeo_departamento', models.CharField(max_length=100, verbose_name='Nombre Ubigeo Departamento')),
                ('continente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubigeo_ubigeodepartamento_continente', to='ubigeo.UbigeoContinente')),
            ],
            options={
                'verbose_name_plural': '3. Ubigeo Departamentos',
            },
        ),
        migrations.CreateModel(
            name='UbigeoDistrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_ubigeo_reniec_distrito', models.CharField(max_length=6, validators=[
                    django.core.validators.RegexValidator(message='Numero de 6 digitos', regex='^[0-9]{6}$')],
                                                                verbose_name='Código Ubigeo Distrito - RENIEC')),
                ('cod_ubigeo_inei_distrito', models.CharField(max_length=6, validators=[
                    django.core.validators.RegexValidator(message='Numero de 6 digitos', regex='^[0-9]{6}$')],
                                                              verbose_name='Código Ubigeo Distrito - INEI')),
                ('ubigeo_distrito', models.CharField(max_length=100, verbose_name='Nombre Ubigeo Distrito')),
                ('continente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubigeo_ubigeodistrito_continente', to='ubigeo.UbigeoContinente')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubigeo_ubigeodistrito_departamento', to='ubigeo.UbigeoDepartamento')),
            ],
            options={
                'verbose_name_plural': '5. Ubigeo Distritos',
            },
        ),
        migrations.CreateModel(
            name='UbigeoLocalidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_ubigeo_reniec_localidad', models.CharField(max_length=10, validators=[
                    django.core.validators.RegexValidator(message='Numero entre 8 y 10 digitos',
                                                          regex='^[0-9]{8,10}$')],
                                                                 verbose_name='Código Ubigeo Localidad - RENIEC')),
                ('cod_ubigeo_inei_localidad', models.CharField(max_length=10, validators=[
                    django.core.validators.RegexValidator(message='Numero entre 8 y 10 digitos',
                                                          regex='^[0-9]{8,10}$')],
                                                               verbose_name='Código Ubigeo Localidad - RENIEC')),
                ('ubigeo_localidad', models.CharField(max_length=100, verbose_name='Nombre Ubigeo Localidad')),
                ('continente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubigeo_ubigeolocalidad_continente', to='ubigeo.UbigeoContinente')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubigeo_ubigeolocalidad_departamento', to='ubigeo.UbigeoDepartamento')),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubigeo_ubigeolocalidad_distrito', to='ubigeo.UbigeoDepartamento')),
            ],
            options={
                'verbose_name_plural': '6. Ubigeo Localidades',
            },
        ),
        migrations.CreateModel(
            name='UbigeoPais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_ubigeo_reniec_pais', models.CharField(max_length=3, validators=[
                    django.core.validators.RegexValidator(message='Numero de 1 o 3 digitos', regex='^[0-9]{1,3}$')],
                                                            verbose_name='Código Ubigeo Pais - RENIEC')),
                ('cod_ubigeo_inei_pais', models.CharField(max_length=3, validators=[
                    django.core.validators.RegexValidator(message='Numero de 1 o 3 digitos', regex='^[0-9]{1,3}$')],
                                                          verbose_name='Código Ubigeo Pais - INEI')),
                ('ubigeo_pais', models.CharField(max_length=100, verbose_name='Nombre Ubigeo Pais')),
                ('continente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubigeo_ubigeopais_continente', to='ubigeo.UbigeoContinente')),
            ],
            options={
                'verbose_name_plural': '2. Ubigeo Paises',
            },
        ),
        migrations.CreateModel(
            name='UbigeoProvincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_ubigeo_reniec_provincia', models.CharField(max_length=4, validators=[
                    django.core.validators.RegexValidator(message='Numero de 4 digitos', regex='^[0-9]{4}$')],
                                                                 verbose_name='Código Ubigeo Provincia - RENIEC')),
                ('cod_ubigeo_inei_provincia', models.CharField(max_length=4, validators=[
                    django.core.validators.RegexValidator(message='Numero de 4 digitos', regex='^[0-9]{4}$')],
                                                               verbose_name='Código Ubigeo Provincia - INEI')),
                ('ubigeo_provincia', models.CharField(max_length=100, verbose_name='Nombre Ubigeo Provincia')),
                ('continente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubigeo_ubigeoprovincia_continente', to='ubigeo.UbigeoContinente')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubigeo_ubigeoprovincia_departamento', to='ubigeo.UbigeoDepartamento')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubigeo_ubigeoprovincia_pais', to='ubigeo.UbigeoPais')),
            ],
            options={
                'verbose_name_plural': '4. Ubigeo Provincias',
            },
        ),
        migrations.AddField(
            model_name='ubigeolocalidad',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubigeo_ubigeolocalidad_pais', to='ubigeo.UbigeoPais'),
        ),
        migrations.AddField(
            model_name='ubigeolocalidad',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubigeo_ubigeolocalidad_provincia', to='ubigeo.UbigeoProvincia'),
        ),
        migrations.AddField(
            model_name='ubigeodistrito',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubigeo_ubigeodistrito_pais', to='ubigeo.UbigeoPais'),
        ),
        migrations.AddField(
            model_name='ubigeodistrito',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubigeo_ubigeodistrito_provincia', to='ubigeo.UbigeoProvincia'),
        ),
        migrations.AddField(
            model_name='ubigeodepartamento',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubigeo_ubigeodepartamento_pais', to='ubigeo.UbigeoPais'),
        ),
    ]
