# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ubigeo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubigeodistrito',
            name='area',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ubigeodistrito',
            name='l_inf',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ubigeodistrito',
            name='l_sup',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ubigeodistrito',
            name='pobreza',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ubigeodistrito',
            name='quintil_20',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ubigeodistrito',
            name='region',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ubigeodistrito',
            name='tiene_friaje',
            field=models.BooleanField(default=False),
        ),
    ]
