# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ubigeo', '0002_auto_20170301_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubigeodistrito',
            name='area',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Urbano'), (2, 'Rural')], null=True),
        ),
        migrations.AlterField(
            model_name='ubigeodistrito',
            name='quintil_20',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ubigeodistrito',
            name='region',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Costa'), (2, 'Sierra'), (3, 'Selva'),
                                                                        (4, 'Lima Metropolitana')], null=True),
        ),
    ]
