# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ubigeo', '0004_ubigeopais_id_pais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubigeopais',
            name='id_pais',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
