# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 16:35
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ubigeo', '0005_auto_20170306_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubigeopais',
            name='continente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='ubigeo_ubigeopais_continente', to='ubigeo.UbigeoContinente'),
        ),
    ]
