# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ubigeo', '0006_auto_20170310_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubigeocontinente',
            name='continente_id',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
    ]
