# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ubigeo', '0008_auto_20170411_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubigeopais',
            name='alpha2',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='ubigeopais',
            name='alpha3',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
