# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ubigeo', '0009_auto_20170411_1444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ubigeocontinente',
            old_name='continente_id',
            new_name='alpha3',
        ),
        migrations.AddField(
            model_name='ubigeocontinente',
            name='alpha2',
            field=models.CharField(default='', max_length=2),
            preserve_default=False,
        ),
    ]
