# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-08 18:26
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ubigeo', '0010_auto_20170411_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubigeolocalidad',
            name='cod_ubigeo_inei_localidad',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='Numero de 9 digitos', regex='^[0-9]{9}$')], verbose_name='Código Ubigeo Localidad - INEI'),
        ),
        migrations.AlterField(
            model_name='ubigeolocalidad',
            name='cod_ubigeo_reniec_localidad',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='Numero de 9 digitos', regex='^[0-9]{9}$')], verbose_name='Código Ubigeo Localidad - RENIEC'),
        ),
        migrations.AlterField(
            model_name='ubigeolocalidad',
            name='distrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubigeo_ubigeolocalidad_distrito', to='ubigeo.UbigeoDistrito'),
        ),
    ]
