# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-11 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstitucionEducativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre')),
                ('codigo_modular',
                 models.CharField(blank=True, max_length=15, null=True, verbose_name='Código modular')),
                ('codigo_colegio',
                 models.CharField(blank=True, max_length=15, null=True, verbose_name='Código colegio')),
                ('ubigeo', models.CharField(blank=True, max_length=10, null=True, verbose_name='Ubigeo')),
                ('nombre_ugel', models.CharField(blank=True, max_length=150, null=True, verbose_name='Ugel')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('establecimiento_codigo',
                 models.CharField(blank=True, max_length=10, null=True, verbose_name='Código establecimiento')),
                ('establecimiento_nombre',
                 models.CharField(blank=True, max_length=255, null=True, verbose_name='Establecimiento')),
                ('tipo',
                 models.CharField(choices=[('1', 'Nido/Jardín'), ('2', 'Escuela'), ('3', 'Colegio')], default='3',
                                  max_length=1)),
            ],
        ),
    ]
