# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-12 11:08
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('establecimiento', '0010_auto_20170424_1240'),
        ('insteducativa', '0002_auto_20170512_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institucioneducativa',
            name='establecimiento_codigo',
        ),
        migrations.RemoveField(
            model_name='institucioneducativa',
            name='establecimiento_nombre',
        ),
        migrations.AddField(
            model_name='institucioneducativa',
            name='establecimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='establecimiento.Establecimiento'),
        ),
        migrations.AlterField(
            model_name='institucioneducativa',
            name='codigo_colegio',
            field=models.CharField(default='', max_length=15, unique=True, verbose_name='Código colegio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='institucioneducativa',
            name='codigo_modular',
            field=models.CharField(default='', max_length=15, unique=True, verbose_name='Código modular'),
            preserve_default=False,
        ),
    ]
