# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-12 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('insteducativa', '0003_auto_20170512_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='institucioneducativa',
            name='tipo',
            field=models.CharField(choices=[('1', 'PRONOEI'), ('2', 'Jardín'), ('3', 'Colegio'), ('4', 'Otro')],
                                   default='3', max_length=1),
        ),
    ]
