# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 13:02
from __future__ import unicode_literals

from django.db import migrations, models

import phr.mpitoken.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_identifier', models.CharField(max_length=50)),
                ('app_name', models.CharField(max_length=250)),
                ('token', models.CharField(editable=False, max_length=32)),
                ('allowed_ips', models.TextField(help_text='Lista de IPs permitidas, separadas por comas.',
                                                 validators=[phr.mpitoken.validators.validate_ip])),
            ],
        ),
    ]
