# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioReniec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namespace', models.CharField(max_length=250, verbose_name='NameSpace')),
                ('urlwsdlservice', models.CharField(max_length=500, verbose_name='UrlWSLD')),
                ('appservice', models.CharField(max_length=100, verbose_name='App')),
                ('userservice', models.CharField(max_length=8, verbose_name='User')),
                ('passservice', models.CharField(max_length=500, verbose_name='Password')),
            ],
            options={
                'verbose_name': 'SERVICIO DNI RENIEC',
                'verbose_name_plural': 'SERVICIOS DNI RENIEC',
            },
        ),
        migrations.CreateModel(
            name='ServicioSis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlwsdlservice', models.CharField(max_length=500, verbose_name='UrlWSLD')),
                ('namespace', models.CharField(max_length=250, verbose_name='NameSpace')),
                ('appservice', models.CharField(max_length=100, verbose_name='App')),
                ('typeservice', models.IntegerField(verbose_name='Type')),
                ('userservice', models.CharField(max_length=8, verbose_name='User')),
                ('passservice', models.CharField(max_length=500, verbose_name='Password')),
            ],
            options={
                'verbose_name': 'SERVICIO SIS MINSA',
                'verbose_name_plural': 'SERVICIOS SIS MINSA',
            },
        ),
    ]
