# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 22:56
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ubigeo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('es_removido', models.BooleanField(default=False, editable=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('codigo', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'verbose_name_plural': '1. Diresas',
            },
        ),
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('es_removido', models.BooleanField(default=False, editable=False)),
                ('codigo_renaes', models.CharField(max_length=8, verbose_name='código Renaes')),
                ('nombre', models.CharField(max_length=150, verbose_name='nombre')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='teléfono')),
                ('direccion', models.CharField(blank=True, max_length=300, null=True, verbose_name='dirección')),
                ('descripcion', models.TextField(blank=True, max_length=150, null=True, verbose_name='Descripción')),
                ('codigo_his', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código HIS')),
                ('lote', models.SmallIntegerField(default=0, verbose_name='lote')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='longitude/latitude')),
                ('ubigeo', models.CharField(blank=True, max_length=8, null=True, verbose_name='ubigeo')),
            ],
            options={
                'verbose_name_plural': '4. Establecimientos',
            },
        ),
        migrations.CreateModel(
            name='EstablecimientoCategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('es_removido', models.BooleanField(default=False, editable=False)),
                ('nombre_categoria', models.CharField(max_length=15, verbose_name='nombre categoria')),
                ('categoria_nivel', models.IntegerField(blank=True, null=True, verbose_name='nivel establecimiento')),
            ],
            options={
                'verbose_name_plural': '5. Establecimiento Categoria',
            },
        ),
        migrations.CreateModel(
            name='Microred',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('es_removido', models.BooleanField(default=False, editable=False)),
                ('codigo', models.CharField(blank=True, max_length=5, null=True, validators=[django.core.validators.RegexValidator(message='Numero de 2 digitos', regex='^[0-9]{2}$')])),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('estado', models.CharField(blank=True, choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('PENDIENTE', 'Pendiente')], max_length=20, null=True, verbose_name='Estados')),
                ('diresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='establecimiento_microred_diresa', to='establecimiento.Diresa')),
            ],
            options={
                'verbose_name_plural': '3. Micro-Redes',
            },
        ),
        migrations.CreateModel(
            name='Red',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('es_removido', models.BooleanField(default=False, editable=False)),
                ('codigo', models.CharField(blank=True, max_length=5, null=True, validators=[django.core.validators.RegexValidator(message='Numero de 2 digitos', regex='^[0-9]{2}$')])),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('estado', models.CharField(blank=True, choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('PENDIENTE', 'Pendiente')], max_length=20, null=True, verbose_name='Estados')),
                ('diresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='establecimiento_red_diresa', to='establecimiento.Diresa')),
            ],
            options={
                'verbose_name_plural': '2. Redes',
            },
        ),
        migrations.AddField(
            model_name='microred',
            name='red',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='establecimiento_microred_red', to='establecimiento.Red'),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='establecimiento_establecimiento_categoria',
                                    to='establecimiento.EstablecimientoCategoria'),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='continente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='establecimiento_establecimiento_continente',
                                    to='ubigeo.UbigeoContinente'),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='establecimiento_establecimiento_departamento',
                                    to='ubigeo.UbigeoDepartamento'),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='diresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='establecimiento_establecimiento_diresa',
                                    to='establecimiento.Diresa'),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='distrito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='establecimiento_establecimiento_distrito',
                                    to='ubigeo.UbigeoDistrito'),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='microred',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='establecimiento_establecimiento_microred', to='establecimiento.Microred'),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='establecimiento_establecimiento_pais', to='ubigeo.UbigeoPais'),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='establecimiento_establecimiento_provincia', to='ubigeo.UbigeoProvincia'),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='red',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='establecimiento_establecimiento_red', to='establecimiento.Red'),
        ),
    ]
