# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('establecimiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microred',
            name='estado',
            field=models.CharField(blank=True, choices=[('1', 'Activo'), ('2', 'Inactivo'), ('3', 'Pendiente')],
                                   max_length=20, null=True, verbose_name='Estados'),
        ),
        migrations.AlterField(
            model_name='red',
            name='estado',
            field=models.CharField(blank=True, choices=[('1', 'Activo'), ('2', 'Inactivo'), ('3', 'Pendiente')],
                                   max_length=20, null=True, verbose_name='Estados'),
        ),
    ]
