# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('establecimiento', '0002_auto_20170301_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6)),
                ('descripcion', models.CharField(max_length=120)),
                ('estado', models.PositiveSmallIntegerField(choices=[(0, 'Inactivo'), (1, 'Activo')])),
            ],
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='servicios',
            field=models.ManyToManyField(to='establecimiento.Servicio'),
        ),
    ]
