# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-24 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0006_auto_20170315_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='microred',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='red',
            name='estado',
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='direccion',
            field=models.TextField(blank=True, null=True, verbose_name='dirección'),
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='telefono',
            field=models.CharField(blank=True, max_length=80, verbose_name='teléfono'),
        ),
    ]
