# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-24 11:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0007_auto_20170424_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establecimiento',
            name='diresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='establecimiento_establecimiento_diresa', to='establecimiento.Diresa'),
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='microred',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='establecimiento_establecimiento_microred', to='establecimiento.Microred'),
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='red',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='establecimiento_establecimiento_red', to='establecimiento.Red'),
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='servicios',
            field=models.ManyToManyField(blank=True, null=True, to='establecimiento.Servicio'),
        ),
    ]
