# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-24 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0008_auto_20170424_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establecimiento',
            name='servicios',
            field=models.ManyToManyField(to='establecimiento.Servicio'),
        ),
    ]
