# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-24 12:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0009_auto_20170424_1125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diresa',
            options={'verbose_name_plural': 'Diresas'},
        ),
        migrations.AlterModelOptions(
            name='establecimiento',
            options={'verbose_name_plural': 'Establecimientos'},
        ),
        migrations.AlterModelOptions(
            name='establecimientocategoria',
            options={'verbose_name_plural': 'Establecimiento Categoria'},
        ),
        migrations.AlterModelOptions(
            name='microred',
            options={'verbose_name_plural': 'Micro-Redes'},
        ),
        migrations.AlterModelOptions(
            name='red',
            options={'verbose_name_plural': 'Redes'},
        ),
    ]
