# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 16:57
from __future__ import unicode_literals

from django.db import migrations, models


def actualiza_establecimientos_influenza(apps, schema_editor):
    establecimientos_model = apps.get_model('establecimiento', 'Establecimiento')
    establecimientos = establecimientos_model.objects.filter(
        departamento__cod_ubigeo_inei_departamento='15').exclude(codigo_renaes='16918')
    for obj in establecimientos:
        obj.tiene_influenza = True
        obj.save()


class Migration(migrations.Migration):
    dependencies = [
        ('establecimiento', '0011_diresa_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='establecimiento',
            name='tiene_influenza',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(actualiza_establecimientos_influenza)
    ]
