# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 14:28
from __future__ import unicode_literals

from django.db import migrations, models


def actualiza_establecimientos_anemia(apps, schema_editor):
    establecimientos_model = apps.get_model('establecimiento', 'Establecimiento')
    establecimientos = establecimientos_model.objects.filter(tiene_influenza=True)
    for obj in establecimientos:
        obj.es_para_anemia = True
        obj.save()


class Migration(migrations.Migration):
    dependencies = [
        ('establecimiento', '0012_establecimiento_tiene_influenza'),
    ]

    operations = [
        migrations.AddField(
            model_name='establecimiento',
            name='es_para_anemia',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(actualiza_establecimientos_anemia)
    ]
