# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0013_establecimiento_es_para_anemia'),
    ]

    operations = [
        migrations.AddField(
            model_name='establecimiento',
            name='es_banco_sangre',
            field=models.BooleanField(default=False),
        ),
    ]
