# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-23 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0014_establecimiento_es_banco_sangre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establecimiento',
            name='lote',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='lote'),
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='servicios',
            field=models.ManyToManyField(blank=True, to='establecimiento.Servicio'),
        ),
    ]
