# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-30 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('establecimiento', '0015_auto_20180123_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='establecimiento',
            name='horario_atencion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Horario de atención'),
        ),
    ]
