# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-05 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0016_establecimiento_horario_atencion'),
    ]

    operations = [
        migrations.AddField(
            model_name='diresa',
            name='es_activo',
            field=models.BooleanField(default=True),
        ),
    ]
