# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 11:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ciudadano', '0024_auto_20170302_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inforrus', models.CharField(blank=True, max_length=20)),
                ('especialidad', models.CharField(blank=True, max_length=300)),
                ('tipo', models.CharField(blank=True, choices=[('MEDICO', 'Médico'), ('TERAPISTA', 'Terapista'), ('ENFERMERO', 'Enfermero')], max_length=300)),
                ('ciudadano', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ciudadano.Ciudadano')),
            ],
        ),
    ]
