# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('personal', '0004_tipopersonal_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='rne',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='especialidad',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='inforhus',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
