# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 22:56
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoAyudaTecnica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoCIE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ciex', models.CharField(max_length=10, unique=True)),
                ('desc_ciex', models.CharField(max_length=200)),
                ('id_sexo', models.CharField(blank=True, max_length=20, null=True)),
                ('id_tipedad_min', models.CharField(blank=True, max_length=10, null=True)),
                ('min_edad', models.CharField(blank=True, max_length=10, null=True)),
                ('id_tipedad_max', models.CharField(blank=True, max_length=10, null=True)),
                ('max_edad', models.CharField(blank=True, max_length=10, null=True)),
                ('fg_tipdiag', models.CharField(blank=True, max_length=10, null=True)),
                ('clase1', models.CharField(blank=True, max_length=10, null=True)),
                ('lab1', models.CharField(blank=True, max_length=10, null=True)),
                ('lab2', models.CharField(blank=True, max_length=10, null=True)),
                ('lab3', models.CharField(blank=True, max_length=10, null=True)),
                ('lab4', models.CharField(blank=True, max_length=10, null=True)),
                ('lab5', models.CharField(blank=True, max_length=10, null=True)),
                ('id_ciex_and', models.CharField(blank=True, max_length=10, null=True)),
                ('id_ciex_or', models.CharField(blank=True, max_length=10, null=True)),
                ('fg_ciex', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoDeficiencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_deficiencia', models.CharField(max_length=10)),
                ('nombre_deficiencia', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoDiscapacidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_discapacidad', models.CharField(max_length=10)),
                ('nombre_discapacidad', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoEtnia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_etnia', models.CharField(max_length=2)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoFinanciador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('descripcion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoGradoInstruccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoProcedimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_grupo', models.CharField(max_length=10)),
                ('nombre_grupo', models.CharField(max_length=200)),
                ('codigo_seccion', models.CharField(blank=True, max_length=10, null=True)),
                ('descripcion_seccion', models.CharField(blank=True, max_length=200, null=True)),
                ('codigo_subseccion', models.CharField(blank=True, max_length=10, null=True)),
                ('subdivision_anatomica', models.CharField(blank=True, max_length=200, null=True)),
                ('codigo_cpt', models.CharField(blank=True, max_length=20, null=True)),
                ('denominacion_procedimientos', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoRaza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='catalogoetnia',
            name='raza',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='catalogo.CatalogoRaza'),
        ),
    ]
