# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 18:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_auto_20170509_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamiliaMedicamentoAntecedenteSugerido',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MedicamentoAntecedenteSugerido',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.FamiliaMedicamentoAntecedenteSugerido')),
            ],
        ),
    ]
