# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-25 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_familiamedicamentoantecedentesugerido_medicamentoantecedentesugerido'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamentoantecedentesugerido',
            name='es_activo',
            field=models.BooleanField(default=True),
        ),
    ]
