# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-09 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ciudadano', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciudadano',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
    ]
