# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-19 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciudadano', '0002_ciudadano_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ciudadanorn',
            options={'verbose_name': '2. Ciudadano RN', 'verbose_name_plural': '2. Ciudadanos RN'},
        ),
        migrations.AlterField(
            model_name='ciudadanorn',
            name='corticoides_antenatales',
            field=models.CharField(blank=True, choices=[('01', 'No recibe'), ('02', 'Completo'), ('03', 'Incompleto')], max_length=2, null=True),
        ),
    ]
