# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-24 12:01
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ciudadano', '0003_auto_20170119_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudadano',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Número de documento'),
        ),
        migrations.AlterField(
            model_name='ciudadanorn',
            name='condicion_parto',
            field=models.CharField(blank=True,
                                   choices=[('00', 'No se conoce'), ('01', 'Espontaneo'), ('02', 'Instrumentado'),
                                            ('03', 'Cesárea'), ('04', 'Otro')], max_length=2, null=True, validators=[
                    django.core.validators.RegexValidator(message='Numero de 2 digitos', regex='^[0-9]{2}$')],
                                   verbose_name='Condición'),
        ),
        migrations.AlterField(
            model_name='ciudadanorn',
            name='terminacion_parto',
            field=models.CharField(blank=True,
                                   choices=[('00', 'No se conoce'), ('01', 'Espontaneo'), ('02', 'Instrumentado'),
                                            ('03', 'Cesárea'), ('04', 'Otro')], max_length=2, null=True, validators=[
                    django.core.validators.RegexValidator(message='Numero de 2 digitos', regex='^[0-9]{2}$')],
                                   verbose_name='Terminación'),
        ),
    ]
