# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-27 18:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ciudadano', '0004_auto_20170124_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ciudadanopaciente',
            name='ciudadano',
        ),
        migrations.AddField(
            model_name='ciudadano',
            name='cui',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='N° CUI'),
        ),
        migrations.AddField(
            model_name='ciudadano',
            name='grado_instruccion',
            field=models.CharField(blank=True, choices=[('00', 'Sin instrucción'), ('01', 'Educación inicial'),
                                                        ('02', 'Primaria completa'), ('03', 'Primaria incompleta'),
                                                        ('04', 'Educación especial'), ('05', 'Secundaria completa'),
                                                        ('06', 'Secundaria cncompleta'),
                                                        ('07', 'Superior técnica completa'),
                                                        ('08', 'Superior técnica incompleta'),
                                                        ('09', 'Superior universitaria completa'),
                                                        ('10', 'Superior universitaria incompleta'),
                                                        ('11', 'Sin información'),
                                                        ('12', 'No corresponde (menores de 3 años)')], max_length=4,
                                   null=True),
        ),
        migrations.AddField(
            model_name='ciudadano',
            name='ocupacion',
            field=models.CharField(blank=True,
                                   choices=[('01', 'Profesional'), ('02', 'Empleado'), ('03', 'Comerciante'),
                                            ('04', 'Obrero'), ('05', 'Ama casa'), ('06', 'Estudiante'),
                                            ('07', 'Sin ocupacion'), ('08', 'Otro')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='ciudadano',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('1', 'Soltero(a)'), ('2', 'Casado(a)'), ('3', 'Conviviente'),
                                                        ('4', 'Divorciado(a)'), ('5', 'Viudo(a)')], max_length=10,
                                   null=True, verbose_name='Estado civil'),
        ),
        migrations.AlterField(
            model_name='ciudadano',
            name='sexo',
            field=models.CharField(blank=True, choices=[('1', 'Masculino'), ('2', 'Femenino')], max_length=2,
                                   null=True, validators=[
                    django.core.validators.RegexValidator(message='Numero de 2 digitos', regex='^[0-9]{2}$')],
                                   verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='ciudadano',
            name='tipo_seguro',
            field=models.PositiveIntegerField(blank=True,
                                              choices=[('00', 'No se conoce'), ('01', 'Usuario'), ('02', 'SIS'),
                                                       ('03', 'Essalud'), ('04', 'Soat'), ('05', 'Sanidad FAP'),
                                                       ('06', 'Sanidad Naval'), ('07', 'Sanidad EP'),
                                                       ('08', 'Sanidad PNP'), ('09', 'Privados'), ('10', 'Otros'),
                                                       ('11', 'Exonerados')], null=True,
                                              verbose_name='Tipo de seguro'),
        ),
        migrations.AlterField(
            model_name='ciudadanorn',
            name='sexo_nacido',
            field=models.CharField(blank=True, choices=[('1', 'Masculino'), ('2', 'Femenino')], max_length=2,
                                   null=True, validators=[
                    django.core.validators.RegexValidator(message='Numero de 2 digitos', regex='^[0-9]{2}$')],
                                   verbose_name='Sexo Nacido'),
        ),
        migrations.DeleteModel(
            name='CiudadanoPaciente',
        ),
    ]
