# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-31 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ciudadano', '0005_auto_20170127_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ciudadano',
            name='uuid',
        ),
        migrations.AlterField(
            model_name='ciudadano',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True,
                                   verbose_name='Número de documento'),
        ),
    ]
