# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-31 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciudadano', '0006_auto_20170131_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudadano',
            name='sexo',
            field=models.CharField(blank=True, choices=[('1', 'Masculino'), ('2', 'Femenino')], max_length=2, null=True, verbose_name='Sexo'),
        ),
    ]
