# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 18:27
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciudadano', '0009_ciudadanorn_etnia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ciudadanorn',
            old_name='etnia',
            new_name='etnia_nacido',
        ),
        migrations.AlterField(
            model_name='ciudadano',
            name='sexo',
            field=models.CharField(blank=True, choices=[('01', 'Masculino'), ('02', 'Femenino')], max_length=2, null=True, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='ciudadano',
            name='tipo_seguro',
            field=models.CharField(blank=True, choices=[('00', 'NO SE CONOCE'), ('01', 'USUARIO'), ('02', 'SIS'), ('03', 'ESSALUD'), ('04', 'S.O.A.T'), ('05', 'SANIDAD F.A.P'), ('06', 'SANIDAD NAVAL'), ('07', 'SANIDAD EP'), ('08', 'SANIDAD PNP'), ('09', 'PRIVADOS'), ('10', 'OTROS'), ('11', 'EXONERADO')], max_length=2, null=True, verbose_name='Tipo de seguro'),
        ),
        migrations.AlterField(
            model_name='ciudadanorn',
            name='financiador_parto',
            field=models.CharField(blank=True, choices=[('00', 'NO SE CONOCE'), ('01', 'USUARIO'), ('02', 'SIS'), ('03', 'ESSALUD'), ('04', 'S.O.A.T'), ('05', 'SANIDAD F.A.P'), ('06', 'SANIDAD NAVAL'), ('07', 'SANIDAD EP'), ('08', 'SANIDAD PNP'), ('09', 'PRIVADOS'), ('10', 'OTROS'), ('11', 'EXONERADO')], max_length=2, null=True, validators=[django.core.validators.RegexValidator(message='Numero de 2 digitos', regex='^[0-9]{2}$')], verbose_name='Financiador Parto'),
        ),
        migrations.AlterField(
            model_name='ciudadanorn',
            name='sexo_nacido',
            field=models.CharField(blank=True, choices=[('01', 'Masculino'), ('02', 'Femenino')], max_length=2, null=True, validators=[django.core.validators.RegexValidator(message='Numero de 2 digitos', regex='^[0-9]{2}$')], verbose_name='Sexo Nacido'),
        ),
    ]
