# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ciudadano', '0011_auto_20170216_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudadanorn',
            name='financiador_parto',
            field=models.CharField(blank=True,
                                   choices=[('0', 'NO SE CONOCE'), ('1', 'USUARIO'), ('2', 'SIS'), ('3', 'ESSALUD'),
                                            ('4', 'S.O.A.T'), ('5', 'SANIDAD F.A.P'), ('6', 'SANIDAD NAVAL'),
                                            ('7', 'SANIDAD EP'), ('8', 'SANIDAD PNP'), ('9', 'PRIVADOS'),
                                            ('10', 'OTROS'), ('11', 'EXONERADO')], max_length=2, null=True,
                                   verbose_name='Financiador Parto'),
        ),
        migrations.AlterField(
            model_name='ciudadanorn',
            name='sexo_nacido',
            field=models.CharField(blank=True, choices=[('1', 'Masculino'), ('2', 'Femenino')], max_length=2,
                                   null=True, verbose_name='Sexo Nacido'),
        ),
    ]
