# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 20:14
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciudadano', '0012_auto_20170216_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudadanorn',
            name='duracion_parto',
            field=models.CharField(blank=True, choices=[('01', 'Normal'), ('02', 'Prolongado'), ('03', 'Precipitado'), ('04', 'No Aplica')], max_length=2, null=True, validators=[django.core.validators.RegexValidator(message='Numero de 2 digitos', regex='^[0-9]{2}$')], verbose_name='Duración'),
        ),
    ]
