# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ciudadano', '0013_auto_20170216_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciudadanorn',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
