# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 15:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ciudadano', '0014_auto_20170217_1502'),
        ('ciudadano', '0014_ciudadanorn_uid'),
    ]

    operations = [
    ]
