# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciudadano', '0015_merge_20170217_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudadanorn',
            name='cui',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='N° CUI'),
        ),
    ]
