# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 18:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ciudadano', '0016_auto_20170217_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudadanorn',
            name='ciudadano',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rns', to='ciudadano.Ciudadano'),
        ),
    ]
