# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ciudadano', '0017_auto_20170217_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciudadano',
            name='foto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
