# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ciudadano', '0018_ciudadano_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudadano',
            name='estado',
            field=models.CharField(blank=True, choices=[('1', 'Activo'), ('2', 'Inactivo'), ('3', 'Pendiente')],
                                   default='PENDIENTE', max_length=1, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='ciudadano',
            name='sexo',
            field=models.CharField(blank=True, choices=[('1', 'Masculino'), ('2', 'Femenino')], max_length=1,
                                   null=True, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='ciudadano',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('00', 'NO SE CONOCE'), ('01', 'DNI/LE'), ('02', 'LM/BO'),
                                                        ('03', 'CARNET DE EXTRAJERIA'), ('04', 'ACTA DE NACIMIENTO'),
                                                        ('06', 'PASAPORTE'), ('07', 'DI DEL EXTRANJERO')],
                                   max_length=2, null=True, verbose_name='Tipo de documento'),
        ),
        migrations.AlterField(
            model_name='ciudadano',
            name='tipo_documento_minsa',
            field=models.CharField(blank=True, choices=[('0', 'No tiene'), ('1', 'DNI'), ('2', 'Carné de extranjería'),
                                                        ('3', 'Pasaporte'),
                                                        ('4', 'Documento de identidad extranjero')], max_length=1,
                                   null=True, verbose_name='Tipo de documento'),
        ),
    ]
