# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ciudadano', '0019_auto_20170301_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudadano',
            name='estado',
            field=models.CharField(blank=True, choices=[('1', 'Activo'), ('2', 'Inactivo'), ('3', 'Pendiente')],
                                   default='1', max_length=1, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='ciudadano',
            name='tipo_documento_minsa',
            field=models.CharField(blank=True, choices=[('0', 'No tiene'), ('1', 'DNI'), ('2', 'Carné de extranjería'),
                                                        ('3', 'Pasaporte'),
                                                        ('4', 'Documento de identidad extranjero')], max_length=2,
                                   null=True, verbose_name='Tipo de documento'),
        ),
    ]
