# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ciudadano', '0021_auto_20170301_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciudadano',
            name='origen_datos',
            field=models.PositiveSmallIntegerField(choices=[(1, 'local'), (2, 'hisminsa')], default=1),
        ),
    ]
