# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ciudadano', '0024_auto_20170302_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudadano',
            name='domicilio_direccion',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Domicilio Direccion'),
        ),
        migrations.AlterField(
            model_name='ciudadano',
            name='domicilio_referencia',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Domicilio Referencia'),
        ),
        migrations.AlterField(
            model_name='ciudadano',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True,
                                   verbose_name='Número de documento'),
        ),
    ]
