# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 14:07
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ubigeo', '0007_ubigeocontinente_continente_id'),
        ('ciudadano', '0028_auto_20170314_1814'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ciudadano',
            options={'verbose_name': 'Ciudadano', 'verbose_name_plural': 'Ciudadanos'},
        ),
        migrations.AddField(
            model_name='ciudadano',
            name='pais_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='pais_origen', to='ubigeo.UbigeoPais'),
        ),
        migrations.AlterField(
            model_name='ciudadano',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Número de documento'),
        ),
        migrations.AlterUniqueTogether(
            name='ciudadano',
            unique_together=set([('tipo_documento', 'numero_documento', 'pais_origen')]),
        ),
    ]
