# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ciudadano', '0029_auto_20170411_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudadano',
            name='origen_datos',
            field=models.PositiveSmallIntegerField(blank=True,
                                                   choices=[(1, 'importado'), (2, 'hisminsa'), (3, 'busqueda reniec'),
                                                            (4, 'cnv'), (5, 'creado')], default=5, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='ciudadano',
            unique_together=set([('tipo_documento', 'numero_documento')]),
        ),
    ]
