# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-25 10:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('ciudadano', '0031_auto_20170424_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='antecedenteciudadano',
            old_name='uid',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='antecedentefamiliar',
            old_name='uid',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='ciudadanorn',
            old_name='uid',
            new_name='uuid',
        ),
        migrations.RemoveField(
            model_name='ciudadano',
            name='uid',
        ),
    ]
