# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-25 10:47
from __future__ import unicode_literals

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ciudadano', '0032_auto_20170425_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciudadano',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
