# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-11 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciudadano', '0037_auto_20170508_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudadano',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('1', 'Soltero(a)'), ('2', 'Casado(a)'), ('3', 'Conviviente'), ('4', 'Divorciado(a)'), ('5', 'Viudo(a)'), ('6', 'Separado(a)')], default='1', max_length=2, null=True, verbose_name='Estado civil'),
        ),
        migrations.AlterField(
            model_name='ciudadanorn',
            name='unida_medida_edad',
            field=models.CharField(blank=True, choices=[('01', 'Horas'), ('02', 'Días')], max_length=2, null=True),
        ),
    ]
