# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-11 11:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ciudadano', '0038_auto_20170511_1053'),
        ('ciudadano', '0038_auto_20170511_0735'),
    ]

    operations = [
    ]
