# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 18:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('ciudadano', '0041_auto_20170613_1428'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ciudadanorn',
            options={'verbose_name': 'Ciudadano RN', 'verbose_name_plural': 'Ciudadanos RN'},
        ),
    ]
