# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ciudadano', '0042_auto_20170614_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciudadanorn',
            name='numero_dni_ciudadano',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
