# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ciudadano', '0043_ciudadanorn_numero_dni_ciudadano'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciudadano',
            name='codigo_asegurado',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='Código de asegurado'),
        ),
    ]
