# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ciudadano', '0044_ciudadano_codigo_asegurado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciudadano',
            name='ultima_actualizacion_tipo_seguro',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
