# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 14:32
from __future__ import unicode_literals

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ciudadano', '0045_ciudadano_ultima_actualizacion_tipo_seguro'),
    ]

    operations = [
        migrations.CreateModel(
            name='CiudadanoDatosSIS',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('contrato', models.CharField(blank=True, max_length=50, null=True)),
                ('correlativo', models.CharField(blank=True, max_length=50, null=True)),
                ('codigo_eess', models.CharField(max_length=8)),
                ('estado', models.CharField(max_length=50)),
                ('disa', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_afiliacion', models.DateField()),
                ('fecha_caducidad', models.DateField(blank=True, null=True)),
                ('id_grupo_poblacional', models.CharField(blank=True, max_length=50, null=True)),
                ('id_numero_registro', models.CharField(blank=True, max_length=50, null=True)),
                ('id_plan', models.CharField(blank=True, max_length=50, null=True)),
                ('nro_contrato', models.CharField(blank=True, max_length=50, null=True)),
                ('regimen', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_formato', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_seguro', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_seguro_descripcion', models.CharField(blank=True, max_length=50, null=True)),
                ('ciudadano',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ciudadano.Ciudadano')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
