# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciudadano', '0047_auto_20170811_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='antecedenteciudadano',
            name='anio_diagnostico',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='antecedenteciudadano',
            name='consulta_paciente',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='antecedenteciudadano',
            name='grupo_antecedente',
            field=models.CharField(choices=[('1', 'Antecedentes personales'), ('2', 'Antecedentes familiares')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='antecedenteciudadano',
            name='registro_antecedente',
            field=models.CharField(choices=[('0', 'No'), ('1', 'Sí'), ('2', 'No sabe')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='antecedenteciudadano',
            name='subgrupo_antecedente',
            field=models.CharField(blank=True, choices=[('1', 'Patológicos'), ('2', 'Lesiones premalignas'), ('3', 'Cáncer'), ('4', 'Salud mental')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='antecedentefamiliar',
            name='consulta_paciente',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='antecedentefamiliar',
            name='grupo_antecedente',
            field=models.CharField(default='2', max_length=1),
        ),
        migrations.AddField(
            model_name='antecedentefamiliar',
            name='registro_antecedente',
            field=models.CharField(choices=[('0', 'No'), ('1', 'Sí'), ('2', 'No sabe')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='antecedentefamiliar',
            name='subgrupo_antecedente',
            field=models.CharField(blank=True, choices=[('1', 'Patológicos'), ('2', 'Lesiones premalignas'), ('3', 'Cáncer'), ('4', 'Salud mental')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='antecedentefamiliar',
            name='parentesco',
            field=models.PositiveSmallIntegerField(choices=[('1', 'Padre'), ('2', 'Madre'), ('3', 'Hermanos'), ('4', 'Otros')]),
        ),
        migrations.AlterField(
            model_name='ciudadanoparentesco',
            name='parentesco',
            field=models.PositiveSmallIntegerField(choices=[('1', 'Padre'), ('2', 'Madre'), ('3', 'Hermanos'), ('4', 'Otros')]),
        ),
    ]
