# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciudadano', '0048_auto_20170816_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antecedenteciudadano',
            name='tipo_antecedente',
            field=models.CharField(blank=True, choices=[('1', 'Personal'), ('2', 'Gineco-Obstetra'), ('3', 'Patológico'), ('4', 'Psicológico')], max_length=1, null=True),
        ),
    ]
