# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 18:24
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ciudadano', '0050_ciudadano_es_persona_viva'),
    ]

    operations = [
        migrations.CreateModel(
            name='AntecedenteMedicacionHabitual',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('familia_medicamento', models.CharField(max_length=10)),
                ('medicamento', models.CharField(max_length=10)),
                ('dosis', models.PositiveSmallIntegerField()),
                ('frecuencia_horas', models.PositiveSmallIntegerField()),
                ('fecha_inicio', models.DateField()),
                ('consulta_paciente', models.UUIDField()),
                ('ciudadano', models.UUIDField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
