# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ciudadano', '0052_auto_20170920_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='AntecedenteReaccionAdversaMedicamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('es_removido', models.BooleanField(default=False, editable=False)),
                ('familia_medicamento', models.CharField(max_length=10)),
                ('medicamento', models.CharField(max_length=10)),
                ('anio_diagnostico', models.CharField(blank=True, max_length=4, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('registro_antecedente', models.CharField(choices=[('0', 'No'), ('1', 'Sí'), ('2', 'No sabe')], default='1', max_length=1)),
                ('consulta_paciente', models.UUIDField()),
                ('ciudadano', models.UUIDField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
