# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-27 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciudadano', '0053_antecedentereaccionadversamedicamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudadano',
            name='etnia',
            field=models.CharField(choices=[('01', 'AYMARA'), ('02', 'URO'), ('03', 'JAQARU, KAWI (JAQI, CAUQUI)'), ('04', 'CHANCAS'), ('05', 'CHOPCCAS'), ('06', "Q'EROS"), ('07', 'WANCAS'), ('08', 'OTROS GRUPOS QUECHUAS DEL AREA ANDINA (II)'), ('09', 'ACHUAR, ACHUAL'), ('10', 'AMAHUACA'), ('11', 'AMAIWERI • KISAMBAERI'), ('12', 'AMARA KAERI'), ('13', 'ANDOA - SHIMIGAE'), ('14', 'ANDOKE'), ('15', 'ARABELLA (CHIRUPINO)'), ('16', 'ARASAIRE'), ('17', 'ASHANINKA'), ('18', 'ASHENINKA'), ('19', 'AWAJUN (AGUARUNA, AENTS)'), ('20', 'BORA (MIAMUNA)'), ('21', 'CACATAIBO (UNI)'), ('22', 'CAHUARANA (MOROCANO)'), ('23', 'CANDOSHI - MURATO'), ('24', 'CAPANAHUA (JUNIKUIN)'), ('25', 'CAQUINTE (POYENISATI)'), ('26', 'CASHINAHUA (JUNIKUIN)'), ('27', 'CHAMICURO (CHAMEKOLO)'), ('28', 'CHITONAHUA'), ('29', 'COCAMA - COCAMILLA'), ('30', 'CUJARE—O (I—APARI)'), ('31', 'CULINA (MADIJA)'), ('32', 'ESE´EJA ("HUARAYO")'), ('33', 'HARAKMBUT'), ('34', 'HUACHIPAIRE'), ('35', 'HUAORANI (TAGAERI, TAROMENANE)'), ('36', 'HUITOTO (INCLUYE MURUI, MENECA, MUNAINE)'), ('37', 'IQUITO'), ('38', 'ISCONAHUA (ICOBAKEBO)'), ('39', 'JEBERO (SHIWIIU, SEWELO)'), ('40', 'JIBARO'), ('41', 'LAMISTO'), ('42', 'MACHIGUENGA (MATSIGENKA)'), ('43', 'MASHCO - PIRO ("MASHCO")'), ('44', 'MASTANAHUA'), ('45', 'MAYORUNA (MATS...)'), ('46', 'MURUNAHUA'), ('47', 'NANTI'), ('48', 'NOMATSIGUENGA'), ('49', 'OCAINA (IVOT´SA)'), ('50', 'OMAGUA'), ('51', 'OREJON (MAI HUNA, MAIJUNA)'), ('52', 'PISABO (MAYO, KANIBO)'), ('53', 'PUKIRIERI'), ('54', 'QUICHUA - QUICHUA RUNA, KICHWA (I)'), ('55', 'RESIGARO'), ('56', 'SAPITERI'), ('57', 'SECOYA (AIDO PAI)'), ('58', 'CHAPRA'), ('59', 'SHARANAHUA / MARINAHUA (ONIKOIN)'), ('60', 'SHAWI (CHAYAHUITA, KANPUNAN, KAMPU PIYAWI)'), ('61', 'SHIPIBO - CONIBO - SHETEBO'), ('62', 'SHUAR'), ('63', 'TAUSHIRO (PINCHE)'), ('64', 'TICUNA (DU<X<GU)'), ('65', 'TOYOERI'), ('66', 'URARINA (ITUKALE, SHIMACO, KACH¡)'), ('67', 'WAMPIS (HUAMBISA)'), ('68', 'YAGUA (YAWA, NIHAMWO)'), ('69', 'YAMINAHUA'), ('70', 'YANESHA ("AMUESHA")'), ('71', 'YINE • YAMI ("PIRO")'), ('72', 'YORA ("NAHUA", "PARQUENAHUA")'), ('73', 'OTROS GRUPOS INDIGENAS AMAZONICOS'), ('80', 'MESTIZO'), ('81', 'AFRO DESCENDIENTE'), ('82', 'ASIATICO DESCENDIENTE'), ('83', 'OTRO')], default='80', max_length=2, verbose_name='Etnia'),
        ),
    ]
