# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 12:47
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ciudadano', '0054_auto_20171027_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudadanorn',
            name='alimentacion',
            field=models.CharField(blank=True, choices=[('01', 'Lactancia materna exclusiva'), ('02', 'Mixta'),
                                                        ('03', 'Artificial')], max_length=2, null=True, validators=[
                django.core.validators.RegexValidator(message='Número de 2 digitos', regex='^[0-9]{2}$')],
                                   verbose_name='alimentacion'),
        ),
        migrations.AlterField(
            model_name='ciudadanorn',
            name='atiende_parto',
            field=models.CharField(blank=True, choices=[('00', 'NO SE CONOCE'), ('01', 'MÉDICO'), ('02', 'OBSTETRA'),
                                                        ('03', 'ENFERMERA (O)'), ('04', 'INTERNA (O)'),
                                                        ('05', 'TÉCNICO SALUD'), ('06', 'PROMOTOR SALUD'),
                                                        ('07', 'PARTERA / COMADRONA'), ('08', 'FAMILIAR'),
                                                        ('09', 'OTRO'), ('10', 'NADIE (AUTOAYUDA)'),
                                                        ('11', 'MÉDICO GINECO-OBSTETRA'), ('16', 'MÉDICO RESIDENTE'),
                                                        ('99', 'NO REGISTRADO')], max_length=2, null=True, validators=[
                django.core.validators.RegexValidator(message='Número de 2 digitos', regex='^[0-9]{2}$')],
                                   verbose_name='Responsable Atención'),
        ),
        migrations.AlterField(
            model_name='ciudadanorn',
            name='condicion_parto',
            field=models.CharField(blank=True,
                                   choices=[('00', 'No se conoce'), ('01', 'Espontáneo'), ('02', 'Instrumentado'),
                                            ('03', 'Cesárea'), ('04', 'Otro')], max_length=2, null=True, validators=[
                    django.core.validators.RegexValidator(message='Número de 2 digitos', regex='^[0-9]{2}$')],
                                   verbose_name='Condición'),
        ),
        migrations.AlterField(
            model_name='ciudadanorn',
            name='deposiciones',
            field=models.CharField(blank=True,
                                   choices=[('01', 'Meconial'), ('02', 'Transaccional'), ('03', 'Amarilla')],
                                   max_length=2, null=True, validators=[
                    django.core.validators.RegexValidator(message='Número de 2 digitos', regex='^[0-9]{2}$')],
                                   verbose_name='Deposiciones'),
        ),
        migrations.AlterField(
            model_name='ciudadanorn',
            name='duracion_parto',
            field=models.CharField(blank=True, choices=[('01', 'Normal'), ('02', 'Prolongado'), ('03', 'Precipitado'),
                                                        ('04', 'No aplica')], max_length=2, null=True, validators=[
                django.core.validators.RegexValidator(message='Número de 2 digitos', regex='^[0-9]{2}$')],
                                   verbose_name='Duración'),
        ),
        migrations.AlterField(
            model_name='ciudadanorn',
            name='grupo_sanguineo',
            field=models.CharField(blank=True, choices=[('01', 'O'), ('02', 'A'), ('03', 'B'), ('04', 'AB')],
                                   max_length=2, null=True, validators=[
                    django.core.validators.RegexValidator(message='Número de 2 digitos', regex='^[0-9]{2}$')],
                                   verbose_name='Grupo Sanguineo'),
        ),
        migrations.AlterField(
            model_name='ciudadanorn',
            name='muerte_intrauterina',
            field=models.CharField(blank=True,
                                   choices=[('01', 'No hubo'), ('02', 'Durante embarazo'), ('03', 'Durante parto'),
                                            ('04', 'Momento desconocido')], default='01', max_length=2, null=True,
                                   validators=[django.core.validators.RegexValidator(message='Número de 2 digitos',
                                                                                     regex='^[0-9]{2}$')],
                                   verbose_name='Muerte intrauterina'),
        ),
        migrations.AlterField(
            model_name='ciudadanorn',
            name='numero_temperatura',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[
                django.core.validators.RegexValidator(message='Número de 2 digitos', regex='^[0-9]{1,2}$'),
                django.core.validators.MinValueValidator(30, django.core.validators.MaxValueValidator(50))]),
        ),
        migrations.AlterField(
            model_name='ciudadanorn',
            name='peso_edad_gestacional',
            field=models.CharField(blank=True, choices=[('01', 'Adecuado'), ('02', 'Pequeño'), ('03', 'Grande')],
                                   max_length=2, null=True, validators=[
                    django.core.validators.RegexValidator(message='Número de 2 digitos', regex='^[0-9]{2}$')]),
        ),
        migrations.AlterField(
            model_name='ciudadanorn',
            name='placenta_parto',
            field=models.CharField(blank=True, choices=[('01', 'Completa'), ('02', 'Incompleta'), ('03', 'Retenida')],
                                   max_length=2, null=True, validators=[
                    django.core.validators.RegexValidator(message='Número de 2 digitos', regex='^[0-9]{2}$')]),
        ),
        migrations.AlterField(
            model_name='ciudadanorn',
            name='posicion_parto',
            field=models.CharField(blank=True, choices=[('01', 'Horizontal'), ('02', 'Vertical'), ('03', 'No aplica')],
                                   max_length=2, null=True, validators=[
                    django.core.validators.RegexValidator(message='Número de 2 digitos', regex='^[0-9]{2}$')],
                                   verbose_name='Posición Parto'),
        ),
        migrations.AlterField(
            model_name='ciudadanorn',
            name='reanimacion_respiratoria',
            field=models.CharField(blank=True, choices=[('00', 'No'), ('01', 'Oxígeno'), ('02', 'Bolsa y máscara'),
                                                        ('03', 'Avanzado')], default='00', max_length=2, null=True,
                                   validators=[django.core.validators.RegexValidator(message='Número de 2 digitos',
                                                                                     regex='^[0-9]{2}$')]),
        ),
        migrations.AlterField(
            model_name='ciudadanorn',
            name='resultado_examen_fisico',
            field=models.CharField(blank=True, choices=[('01', 'Normal'), ('02', 'Patologico')], max_length=2,
                                   null=True, validators=[
                    django.core.validators.RegexValidator(message='Número de 2 digitos', regex='^[0-9]{2}$')]),
        ),
        migrations.AlterField(
            model_name='ciudadanorn',
            name='terminacion_parto',
            field=models.CharField(blank=True,
                                   choices=[('00', 'No se conoce'), ('01', 'Espontáneo'), ('02', 'Instrumentado'),
                                            ('03', 'Cesárea'), ('04', 'Otro')], max_length=2, null=True, validators=[
                    django.core.validators.RegexValidator(message='Número de 2 digitos', regex='^[0-9]{2}$')],
                                   verbose_name='Terminación'),
        ),
        migrations.AlterField(
            model_name='ciudadanorn',
            name='tipo_egreso',
            field=models.CharField(blank=True, choices=[('01', 'Sano'), ('02', 'Translado'), ('03', 'Con patología'),
                                                        ('04', 'Fallecido')], max_length=35, null=True,
                                   verbose_name='Tipo Egreso'),
        ),
        migrations.AlterField(
            model_name='ciudadanorn',
            name='tipo_parto',
            field=models.CharField(blank=True,
                                   choices=[('01', 'Único'), ('02', 'Doble'), ('03', 'Triple'), ('04', 'Más de tres')],
                                   max_length=2, null=True, validators=[
                    django.core.validators.RegexValidator(message='Número de 2 digitos', regex='^[0-9]{2}$')],
                                   verbose_name='Alumbramiento'),
        ),
    ]
