# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ciudadano', '0055_auto_20171109_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciudadanorn',
            name='codigo_renaes_adscrito',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
