# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 09:29
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciudadano', '0056_ciudadanorn_codigo_renaes_adscrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudadanorn',
            name='talla_nacido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(25), django.core.validators.MaxValueValidator(99)]),
        ),
    ]
