# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-19 18:00
from __future__ import unicode_literals

from django.db import migrations, models


def llenar_anio_inicio_antecedente(apps, schema_editor):
    AntecedenteModel = apps.get_model('ciudadano', 'AntecedenteMedicacionHabitual')
    antecedentes = AntecedenteModel.objects.all().iterator()
    for antecedente in antecedentes:
        antecedente.anio_inicio = antecedente.fecha_inicio.year
        antecedente.save()


def llenar_anio_inicio_antecedente_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('ciudadano', '0058_auto_20171206_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='antecedentemedicacionhabitual',
            name='anio_inicio',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='antecedentemedicacionhabitual',
            name='familia_medicamento',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='antecedentemedicacionhabitual',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RunPython(llenar_anio_inicio_antecedente, llenar_anio_inicio_antecedente_reverse)
    ]
