# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-23 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciudadano', '0059_auto_20180119_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antecedentemedicacionhabitual',
            name='dosis',
            field=models.CharField(max_length=250),
        ),
    ]
