# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-19 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciudadano', '0063_auto_20180525_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudadano',
            name='etnia',
            field=models.CharField(choices=[('01', 'Achuar'), ('02', 'Aimara'), ('03', 'Amahuaca'), ('04', 'Arabela'), ('05', 'Ashaninka'), ('06', 'Asheninka'), ('07', 'Awajún'), ('08', 'Bora'), ('09', 'Capanahua'), ('10', 'Cashinahua'), ('11', 'Chamicuro'), ('12', 'Chapra'), ('13', 'Chitonahua'), ('14', 'Ese eja'), ('15', 'Harakbut'), ('16', 'Ikitu'), ('17', 'Iñapari'), ('18', 'Isconahua'), ('19', 'Jaqaru'), ('20', 'Jíbaro'), ('21', 'Kakataibo'), ('22', 'Kakinte'), ('23', 'Kandozi'), ('24', 'Kichwa'), ('25', 'Kukama kukamiria'), ('26', 'Madija'), ('27', 'Maijuna'), ('28', 'Marinahua'), ('29', 'Mashco Piro'), ('30', 'Mastanahua'), ('31', 'Matsés'), ('32', 'Matsigenka'), ('33', 'Muniche'), ('34', 'Murui-muinanɨ'), ('35', 'Nahua'), ('36', 'Nanti'), ('37', 'Nomatsigenga'), ('38', 'Ocaina'), ('39', 'Omagua'), ('40', 'Quechuas'), ('41', 'Resígaro'), ('42', 'Secoya'), ('43', 'Sharanahua'), ('44', 'Shawi'), ('45', 'Shipibo-konibo'), ('46', 'Shiwilu'), ('47', 'Tikuna'), ('48', 'Urarina'), ('49', 'Uro'), ('50', 'Vacacocha'), ('51', 'Wampis'), ('52', 'Yagua'), ('53', 'Yaminahua'), ('54', 'Yanesha'), ('55', 'Yine'), ('56', 'Afrodescendiente'), ('57', 'Blanco'), ('58', 'Mestizo'), ('59', 'Otro'), ('60', 'No sabe / No responde')], default='58', max_length=2, verbose_name='Etnia'),
        ),
        migrations.AlterField(
            model_name='ciudadanorn',
            name='etnia_nacido',
            field=models.CharField(choices=[('01', 'Achuar'), ('02', 'Aimara'), ('03', 'Amahuaca'), ('04', 'Arabela'), ('05', 'Ashaninka'), ('06', 'Asheninka'), ('07', 'Awajún'), ('08', 'Bora'), ('09', 'Capanahua'), ('10', 'Cashinahua'), ('11', 'Chamicuro'), ('12', 'Chapra'), ('13', 'Chitonahua'), ('14', 'Ese eja'), ('15', 'Harakbut'), ('16', 'Ikitu'), ('17', 'Iñapari'), ('18', 'Isconahua'), ('19', 'Jaqaru'), ('20', 'Jíbaro'), ('21', 'Kakataibo'), ('22', 'Kakinte'), ('23', 'Kandozi'), ('24', 'Kichwa'), ('25', 'Kukama kukamiria'), ('26', 'Madija'), ('27', 'Maijuna'), ('28', 'Marinahua'), ('29', 'Mashco Piro'), ('30', 'Mastanahua'), ('31', 'Matsés'), ('32', 'Matsigenka'), ('33', 'Muniche'), ('34', 'Murui-muinanɨ'), ('35', 'Nahua'), ('36', 'Nanti'), ('37', 'Nomatsigenga'), ('38', 'Ocaina'), ('39', 'Omagua'), ('40', 'Quechuas'), ('41', 'Resígaro'), ('42', 'Secoya'), ('43', 'Sharanahua'), ('44', 'Shawi'), ('45', 'Shipibo-konibo'), ('46', 'Shiwilu'), ('47', 'Tikuna'), ('48', 'Urarina'), ('49', 'Uro'), ('50', 'Vacacocha'), ('51', 'Wampis'), ('52', 'Yagua'), ('53', 'Yaminahua'), ('54', 'Yanesha'), ('55', 'Yine'), ('56', 'Afrodescendiente'), ('57', 'Blanco'), ('58', 'Mestizo'), ('59', 'Otro'), ('60', 'No sabe / No responde')], default='58', max_length=2, null=True, verbose_name='Etnia RN'),
        ),
    ]
