# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-25 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionConexionInternet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conexion_reniec', models.BooleanField(default=True)),
                ('conexion_migraciones', models.BooleanField(default=True)),
                ('conexion_sis', models.BooleanField(default=True)),
                ('ping_time', models.FloatField(default=150.0)),
            ],
            options={
                'verbose_name': 'Configuración de conexión a Internet',
                'verbose_name_plural': 'Configuraciones de conexión a Internet',
            },
        ),
    ]
