# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-05 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracionconexioninternet',
            options={'verbose_name': 'Configuración de conexión a Internet', 'verbose_name_plural': 'Configuración de conexión a Internet'},
        ),
        migrations.RemoveField(
            model_name='configuracionconexioninternet',
            name='conexion_migraciones',
        ),
        migrations.RemoveField(
            model_name='configuracionconexioninternet',
            name='conexion_reniec',
        ),
        migrations.RemoveField(
            model_name='configuracionconexioninternet',
            name='conexion_sis',
        ),
        migrations.AddField(
            model_name='configuracionconexioninternet',
            name='con_conexion',
            field=models.BooleanField(default=True, help_text='Conexión disponible a Internet', verbose_name='Con conexión'),
        ),
    ]
